micronaut:
  application:
    name: cadastroLivro
  server:
    port: 8080

cassandra:
  default:
    basic:
      contact-points:
        - "127.0.0.1:9042"
      session-keyspace: estoque
      load-balancing-policy:
        local-datacenter: datacenter1

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS